
public class ClintonException extends Exception {
	
	//just for fun
	public ClintonException(String s) {
		super("THE RESULT OF THE NOVEMBER ELECTIONS GIVES THE IMAGE OF A DIVIDED AMERICA. THAT THE OUTCOME OF THE CONSULTATION WOULD STILL LEAVE A LARGE SECTION OF THE ELECTORATE UNSATISFIED WAS CLEAR FROM THE START OF THE ELECTION CAMPAIGN, PROBABLY THE MOST VIOLENT IN AMERICAN HISTORY.\n "
				+ "UNEXPECTED, HOWEVER, WAS THE AVALANCHE VICTORY OF DONALD TRUMP, AN UNWELCOME CANDIDATE FOR HIS OWN PARTY, WHO, WITH HIS DIVISIVE STYLE, WAS ABLE TO INTERPRET THE MALAISE OF A COUNTRY IN WHICH SOCIAL AND ECONOMIC CONTRADICTIONS HAVE DRAMATICALLY INCREASED IN RECENT YEARS. SHARPEN. \n"
				+ "THE ANALYSIS OF THE US VOTE COULD BE SUMMARIZED BY THE OBSERVATION OF THE UPRISING OF THE VOTERS OF BOTH PARTIES AGAINST A SYSTEM CONSIDERED CORRUPT AND AFFECTED BY SELF-REFERENTIALISM, TO WHOSE CANDIDATES THEY PREFERRED OUTSIDERS WITH DISTINCTLY RADICAL ORIENTATIONS.\n "
				+ "IN THE WORDS OF THE AMERICAN POLITICAL SCIENTIST FRANCIS FUKUYAMA <<THE REAL STORY OF THIS ELECTION IS THAT AFTER SEVERAL DECADES, AMERICAN DEMOCRACY IS FINALLY RESPONDING TO THE RISE OF INEQUALITY AND THE ECONOMIC STAGNATION EXPERIENCED BY MOST OF THE POPULATION>> \n" 
				+ "1 TRUMP, THEREFORE, AS A REACTION OF AMERICAN DEMOCRACY TO THE CRISIS OF THAT VERY DEMOCRACY. AMONG OTHER THINGS, THESE ELECTIONS ALSO MARK THE DEFINITIVE DECLINE OF TRADITIONAL AMERICAN PARTIES, OVERWHELMED BY THE WAVE OF POPULISM, THE RESULT OF YEARS OF INACTION AND INDIFFERENCE TO THE DEEP WOUNDS THAT HAVE LACERATED THE SOCIAL FABRIC OF THE COUNTRY. \n "
				+ "THE CASUAL OBSERVER OF THE US SYSTEM CAPTURES IN THE ELECTION OF A CONTROVERSIAL CANDIDATE LIKE DONALD TRUMP ONLY PART OF THE LESSON THAT THIS COUNTRY ONCE AGAIN DELIVERS TO HISTORY."
				+ "THE PRESIDENTIAL ELECTIONS THIS AUTUMN ARE A WARNING TO THE RULING CLASSES, INCLUDING EUROPEAN ONES, TO GIVE A CHANGE OF PACE IN THE READING OF SOCIAL PHENOMENA IF THEY DO NOT WANT TO BE SWEPT AWAY BY THE VARIOUS NATIONAL TRUMP.\n"
				+ "TRUMP'S ELECTION TO THE PRESIDENCY OF THE UNITED STATES HAS BEEN MUCH DISCUSSED AND DOES NOT FAIL TO PROVOKE HEATED DEBATES AND PROTESTS A FEW DAYS AFTER HIS INAUGURATION IN THE WHITE HOUSE. "
				+ "WHAT IS INDIGESTIBLE ARE NOT ONLY SOME ASPECTS STRICTLY CONNECTED TO THE PERSON OF THE NEWLY ELECTED PRESIDENT, BUT ALSO THE PECULIAR PROCESS OF ELECTION OF THE PRESIDENT AND THE ANOMALIES THAT THIS PRESENTS.\n"
				+ "DONALD TRUMP IS THE PRESIDENT-ELECT WITH THE LOWEST POPULAR CONSENSUS IN US HISTORY, MARKED BY FOUR OTHER CASES IN WHICH THE WINNING CANDIDATE DID NOT OBTAIN A MAJORITY IN THE POPULAR VOTE. \n"
				+ "THREE OCCURRED IN THE 19TH CENTURY, ON THE OCCASION OF THE ELECTIONS OF 18242, 18763 AND 1888. THE FIRST TWO HIGHLIGHTED THE WEAKNESSES OF THE ELECTORAL SYSTEM, LEADING THE COUNTRY, IN BOTH CASES, TOWARDS SERIOUS CONSTITUTIONAL CRISES AND ON THE BRINK. \n"
				+ "OF THE CIVIL WAR. IN MORE RECENT YEARS, THE 2000 ELECTION IS REMEMBERED WHEN GEORGE W. BUSH SNATCHED VICTORY FROM AL GORE JR., SECURING THE ELECTORAL COLLEGE VOTE BUT NOT THE POPULAR ONE.\n THE AFFAIR, WHICH WAS ALSO THE OCCASION FOR A FAMOUS INTERVENTION BY THE SUPREME COURT ON ELECTORAL MATTERS, CONTINUES TO EXERT A CERTAIN INFLUENCE ON THE AMERICAN POLITICAL DEBATE.");
		
	}

}
